### ISSUE TITLE
akamai_token_validate off

### ISSUE THREAD

**Issue by xXxSPYxXx** [kaltura/nginx-akamai-token-validate-module#15]
Hello,
akamai_token_validate off;
This didnt work.

**Comment by erankor** [comment]
That is correct, this parameter used to be a boolean, but at some point we changed it to contain an expression that is used to get the token value. E.g. `$arg_token` for query string token or `$cookie_token`.

**Comment by xXxSPYxXx** [comment]
It's possible use "off" and $args?

**Comment by erankor** [comment]
To make sure I understand what you're trying to do - you have this param in some high level (e.g. http / server) and you want to disable it for some specific locations?
I can probably add a condition that says - if the param evaluates to `off` and it doesn't use any nginx variables then skip the validation. The second part is required since I don't want to allow sending `?token=off` on the URL, for example.

**Comment by xXxSPYxXx** [comment]
I am need disable token fo CDN provider. I am make it on map
```
map $cdn $akamai_token_state {
 default        $cur_token;
 "~1"           off;
}

```
and after
`akamai_token_validate $akamai_token_state;`

**Comment by erankor** [comment]
this sounds problematic, what will prevent someone from sending you `off` and going around the protection?

**Comment by xXxSPYxXx** [comment]
Yes, it possible. It`s need additations protection. Any way i am setup different server{} for CDN if it has secure issue.

**Comment by erankor** [comment]
I think it's problematic to support `off`, since it means the most common setup becomes trivially hackable. A simple solution for your use case is to just generate an empty token (no exp, acl etc.) and use it instead of `off`
