### ISSUE TITLE
IP validation

### ISSUE THREAD

**Issue by phillipseamore** [kaltura/nginx-akamai-token-validate-module#5]
Is IP validation not supported?  I've tried many times and it doesn't seem to be checked (i.e. ip=192.168.13.201/32 but can still use token from any IP).

**Comment by kaltura-hooks** [comment]
Hi @phillipseamore,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by erankor** [comment]
Hi @phillipseamore, yes, that is correct, this module does not validate the ip address, only `st`, `exp` and `acl` are validated. It's a simple change to add support for ip, but it's very low priority for us at the moment. If anyone would like to submit a pull request for this we'll be happy to merge it.

**Comment by xXxSPYxXx** [comment]
@erankor plz add ip validate.

**Comment by erankor** [comment]
@xXxSPYxXx, had some time to add this feature... 
try this pull - https://github.com/kaltura/nginx-akamai-token-validate-module/pull/14

**Comment by xXxSPYxXx** [comment]
@erankor  its work, thy.

**Comment by erankor** [comment]
Merged, thanks for the update
